const image = document.querySelector('img');
image.src = "https://tse3.mm.bing.net/th/id/OIP.jsdpmXEcmGQvgRauxLdN2AHaDt?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3";
image.alt = "Book image";
image.width = 250;
image.height = 250;
image.style.borderRadius = "5px";
image.style.padding = "20px";
image.style.backgroundColor = "gold";
image.style.color = "red";
const h4 = document.createElement('h4');
h4.textContent = "Title : Physics";
h4.style.marginTop = "10px";
const h3 = document.createElement('h3');    
h3.textContent = "Author : Resnick";
h3.innerText = "Price : 500";
const btn = document.createElement('button');
btn.textContent = "Add to cart";
const child = document.querySelector('div');
child.className = "card";
child.appendChild(image);
child.appendChild(h4);
child.appendChild(h3);
child.appendChild(btn);
const parent = document.querySelector('body');
parent.appendChild(child);